NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
VERSION="2.0.0"

ACCOUNTS=[
  "GAAFRH6KWKXFXN7GR26QWJGYNQLNYY5RHG3YEX42E7ZKJQK2437QLHCP"
]

[DOCUMENTATION]
ORG_NAME="Stellar Quest L2Q3"
ORG_URL="https://stellar.org"
ORG_DESCRIPTION="Quest Level 2 - Quest 3"
ORG_KEYBASE="stellar"
ORG_GITHUB="stellar"
ORG_TWITTER="StellarOrg"
